sonar.projectKey=notification-frontend
sonar.projectName=Notification Frontend
sonar.sources=notification-frontend/src
sonar.tests=notification-frontend/src,notification-frontend/e2e
sonar.test.inclusions=notification-frontend/src/**/*.spec.ts,notification-frontend/e2e/**/*.spec.ts
sonar.javascript.lcov.reportPaths=notification-frontend/coverage/lcov.info
sonar.typescript.tsconfigPaths=notification-frontend/tsconfig.json
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/coverage/**,**/test-results/**,**/*.spec.ts
