sonar.projectKey=notification-worker
sonar.projectName=Notification Worker
sonar.sources=notification-worker/src
sonar.tests=notification-worker/tests
sonar.rust.cargo.manifestPaths=notification-worker/Cargo.toml
sonar.rust.clippy.enabled=false
sonar.rust.clippyReport.reportPaths=notification-worker/target/sonar-clippy.json
sonar.rust.lcov.reportPaths=target/sonar-worker-rust-lcov.info
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/coverage/**,**/test-results/**
