apiVersion: v1
kind: Secret
metadata:
  name: notification-system-local
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  CALLER_API_KEY: {{ .Values.api.key | quote }}
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.username | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.password | quote }}
